### ISSUE TITLE
Sandbox mode?

### ISSUE THREAD

**Issue by tjwoon** [MOLPay/Seamless_Integration#10]
The Android XDK has the following parameter:

```
    // Optional for sandboxed development environment, set boolean value to enable.
    paymentDetails.put(MOLPayActivity.mp_sandbox_mode, true);
```

How do we set this parameter in the Seamless Integration SDK?

**Comment by apis17** [comment]
Hi Tjwoon,

For sandbox seamless integration, please change URL from www.onlinepayment.com.my to sandbox.molpay.com

**Comment by tjwoon** [comment]
Ok, thanks 😀

**Comment by tjwoon** [comment]
Sorry, wait. I don't see option to change the URL in [the documentation](https://github.com/MOLPay/Seamless_Integration/wiki/MOLPay-Seamless-Integration-v3.0%28PCI%29)

**Comment by apis17** [comment]
Hi Tjwoon,

Please check latest seamless update version here: https://github.com/MOLPay/Seamless_Integration/wiki/Latest-MOLPay-Seamless-Integration-(non-PCI)

There are some remarks, demo download and demo URL for sandbox account.

Thank you.

**Comment by tjwoon** [comment]
Hi @apis17 . Thank you! Tested and working.
