### ISSUE TITLE
Boost e-wallet Payment Error : Your transaction has been denied due to merchant account issue (P02)

### ISSUE THREAD

**Issue by jerrychong25** [MOLPay/Seamless_Integration#13]
Hi all,

I would like to test **MOLPay Seamless Integration** for **Boost e-wallet payment** if it is working with my current e-commerce website.

However, it comes with following errors:
<img width="457" alt="Screenshot 2019-06-23 at 10 07 37 AM" src="https://user-images.githubusercontent.com/15714095/59970657-c55ba600-959e-11e9-9e2d-583228a321d8.png">

Source Code:
```
<!-- jQuery (necessary for Razer Merchant Services Seamless JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://www.onlinepayment.com.my/MOLPay/API/seamless/latest/js/MOLPay_seamless.deco.js"></script>
```

`<button type="button" id="myPay" class="btn btn-primary btn-lg" data-toggle="molpayseamless" data-mpsmerchantid="molpaymerchant" data-mpschannel="BOOST" data-mpsamount="1.20" data-mpsorderid="TEST728638391" data-mpsbill_name="MOLPay Technical" >Pay by Boost</button>`

Is there any test Merchant ID available that could proceed to Boost payment screen?

FYI. I have not registered with MOLPay as of now.

Thanks.

**Comment by fayra** [comment]
Hi jerrychong, please drop an email to our support team (support-sa@razer.com) to create the development account and enable BOOST channel. Thank you.

**Comment by jerrychong25** [comment]
> support-sa@razer.com

Hi @fayra,

Noted.

I have sent an email to your support team (support-sa@razer.com).

Thanks.

**Comment by aimensasi** [comment]
Is e-wallet supported for sandbox mode
